### ISSUE TITLE
Unrecognized command

### ISSUE THREAD

**Issue by nassimbenhabib** [syroco/orca#15]
Hello,
Can you help me solve my problem with Orca please?
I installed Orca and its dependencies according to the guide.
But I have a problem when I want to use existing examples:
$ 06-trajectory_following /home/nbenhabib/orca/examples/resources/lwr.urdf
        06-trajectory_following: command not found
Or :
$ rosrun orca 06-trajectory_following /home/nbenhabib/orca/examples/resources/lwr.urdf 
[rosrun] Couldn't find executable named 06-trajectory_following below /home/nbenhabib/orca
     [rosrun] Found the following, but they're either not files,
     [rosrun] or not executable:
     [rosrun]   /home/nbenhabib/orca/build/devel/lib/orca/06-trajectory_following

Executables exist but ubuntu do not consider them as a command.

Thank you!

**Comment by ahoarau** [comment]
Looks like you are in a `non-ros` environnement. 
Then in the build directory there should be an executable, you need to add the full path to it (ex) : 
`~/orca/build/idont/know/the/full/path/06-trajectory_following ~/orca/examples/resources/lwr.urdf`
