### ISSUE TITLE
Error running demo code 02-using_callbacks.cc

### ISSUE THREAD

**Issue by RemcoVDoorn** [syroco/orca#16]
I am new to ORCA and trying to run the example codes.
When i run 02-using_callbacks.cc I get the error:
 _/usr/local/include/orca/utils/Utils.h:153: Parameter 'servo_controller' : /usr/local/include/orca/utils/Utils.h:153: Trying to get() but parameter is not set_

I tried using the various resource files in /orca/examples/resources but the error comes up with all but one of them (panda.urdf yields a different error regarding the base frame). 

I could really use some input on how to solve this. Thanks in advance!

**Comment by ahoarau** [comment]
fixed in 104127a44740dc456d3622d6d780070e401d395c
Thanks !
