### ISSUE TITLE
how to recover the term jdot*qdot ?

### ISSUE THREAD

**Issue by ZzhengP** [syroco/orca#4]
Hello, 
I need recover the term jdot*qdot to compute energy of the effector. But i didn't find it in RobotDyn Class. 
Thank you.  
ZHENG Pu

**Comment by ahoarau** [comment]
```
Eigen::Matrix<double,6,1> jdot_qdot;
jdot_qdot = robot->getFrameBiasAcc("link_7")
```

**Comment by ZzhengP** [comment]
thank you.
