### ISSUE TITLE
How to recover the term joint acceleration ?

### ISSUE THREAD

**Issue by ZzhengP** [syroco/orca#8]
Hello,
I need recover the term joint acceleration to compute the cartesian acceleration of the effector. But i didn't find it in RobotDyn Class.
Thank you.
ZHENG Pu

**Comment by ZzhengP** [comment]
It can be compute by the dynamic equation. 
![codecogseqn](https://user-images.githubusercontent.com/36111459/38300119-41791666-37fc-11e8-8629-7facdd76243c.gif)

**Comment by ahoarau** [comment]
exactly, it is an estimation though. As the mass matrix might not be 100% accurate, and the torque sensing either.

**Comment by ahoarau** [comment]
Why do you need this term ?

**Comment by ZzhengP** [comment]
I need this term to compute the derivative of the jacobian in another point.
